# Keras로 Linear&Logistic Regression 맛보기!

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [45]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [46]:
x = np.array(range(0,20)) 
y = x * 2 -1

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [47]:
x.shape, y.shape

((20,), (20,))

In [48]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1)(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 컴파일 해주렴
model.compile(loss = 'mse', optimizer = 'adam')

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

In [23]:
# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]
[9.9961720e-03 9.7344452e-01 1.9368929e+00 2.9003413e+00 3.8637896e+00
 4.8272376e+00 5.7906861e+00 6.7541342e+00 7.7175827e+00 8.6810312e+00
 9.6444798e+00 1.0607928e+01 1.1571377e+01 1.2534825e+01 1.3498273e+01
 1.4461721e+01 1.5425170e+01 1.6388618e+01 1.7352066e+01 1.8315516e+01]


## Now, Your turn!

In [36]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [37]:
x = np.array(range(0,20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [39]:
keras.backend.clear_session()

input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1)(input_layer)

model = keras.models.Model(inputs = input_layer, outputs = output_layer)

model.compile(loss='mse', optimizer='adam')

In [40]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 284ms/step - loss: 184.7472
Epoch 2/10
1/1 [==============================] - 0s 6ms/step - loss: 184.4520
Epoch 3/10
1/1 [==============================] - 0s 5ms/step - loss: 184.1571
Epoch 4/10
1/1 [==============================] - 0s 5ms/step - loss: 183.8626
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 183.5683
Epoch 6/10
1/1 [==============================] - 0s 5ms/step - loss: 183.2743
Epoch 7/10
1/1 [==============================] - 0s 5ms/step - loss: 182.9807
Epoch 8/10
1/1 [==============================] - 0s 6ms/step - loss: 182.6873
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 182.3944
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 182.1017


In [42]:
model.predict(x)[:5].reshape(-1)

array([-0.00999574, -1.120307  , -2.2306182 , -3.3409295 , -4.451241  ],
      dtype=float32)

In [41]:
y[:5].reshape(-1)

array([10,  7,  4,  1, -2])

## Quick Logistic Regression!

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

In [43]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)


# 컴파일 해주렴
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [44]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

Epoch 1/10
1/1 [==============================] - 0s 500ms/step - loss: -222.0418 - accuracy: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 9ms/step - loss: -222.3360 - accuracy: 0.0000e+00
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: -222.6301 - accuracy: 0.0000e+00
Epoch 4/10
1/1 [==============================] - 0s 7ms/step - loss: -222.9242 - accuracy: 0.0000e+00
Epoch 5/10
1/1 [==============================] - 0s 7ms/step - loss: -223.2183 - accuracy: 0.0000e+00
Epoch 6/10
1/1 [==============================] - 0s 16ms/step - loss: -223.5124 - accuracy: 0.0000e+00
Epoch 7/10
1/1 [==============================] - 0s 10ms/step - loss: -223.8065 - accuracy: 0.0000e+00
Epoch 8/10
1/1 [==============================] - 0s 8ms/step - loss: -224.1007 - accuracy: 0.0000e+00
Epoch 9/10
1/1 [==============================] - 0s 12ms/step - loss: -224.3947 - accuracy: 0.0000e+00
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - lo

[4.9750003e-01 3.0444628e-01 1.6213506e-01 7.8808933e-02 3.6443919e-02
 1.6446382e-02 7.3383451e-03 3.2576323e-03 1.4428496e-03 6.3836575e-04
 2.8228760e-04 1.2487173e-04 5.5199176e-05 2.4403691e-05 1.0788932e-05
 4.7698136e-06 2.1087462e-06 9.3228192e-07 4.1216413e-07 1.8221877e-07]


## Now, Your turn!

In [49]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [50]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [51]:
x.shape, y.shape

((40,), (40,))

In [53]:
keras.backend.clear_session()

il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1, activation='sigmoid',)(il)

model = keras.models.Model(inputs=il, outputs=ol)

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [54]:
model.fit(x, y, epochs=10, verbose=1) # 마지막 epochs를 반영함

Epoch 1/10
2/2 [==============================] - 0s 5ms/step - loss: 2.1977 - accuracy: 0.5250
Epoch 2/10
2/2 [==============================] - 0s 9ms/step - loss: 2.1882 - accuracy: 0.5250
Epoch 3/10
2/2 [==============================] - 0s 7ms/step - loss: 2.1789 - accuracy: 0.5250
Epoch 4/10
2/2 [==============================] - 0s 5ms/step - loss: 2.1685 - accuracy: 0.5250
Epoch 5/10
2/2 [==============================] - 0s 5ms/step - loss: 2.1595 - accuracy: 0.5250
Epoch 6/10
2/2 [==============================] - 0s 6ms/step - loss: 2.1498 - accuracy: 0.5250
Epoch 7/10
2/2 [==============================] - 0s 6ms/step - loss: 2.1404 - accuracy: 0.5250
Epoch 8/10
2/2 [==============================] - 0s 4ms/step - loss: 2.1305 - accuracy: 0.5250
Epoch 9/10
2/2 [==============================] - 0s 4ms/step - loss: 2.1204 - accuracy: 0.5250
Epoch 10/10
2/2 [==============================] - 0s 10ms/step - loss: 2.1108 - accuracy: 0.5250


In [55]:
model.predict(x)[:5].reshape(-1)

array([0.49525937, 0.6019144 , 0.69969785, 0.7821553 , 0.8469248 ],
      dtype=float32)

In [56]:
y[:5].reshape(-1)

array([0, 0, 0, 0, 0])