# Keras로 Linear&Logistic Regression 맛보기!

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [2]:
x = np.array(range(0,20))
y = x * 2 -1 

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [12]:
x.shape, y.shape

((20,), (20,))

In [3]:
# 1번 청소 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
keras.backend.clear_session()

# 2번 모델 선언
model = keras.models.Sequential()

# 3번 모델 블록 조립
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1) )

## 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,)) )

# 4번 컴파일 
model.compile(loss='mse',
              optimizer='adam')

In [4]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 374ms/step - loss: 1052.5520
Epoch 2/10
1/1 [==============================] - 0s 8ms/step - loss: 1051.7761
Epoch 3/10
1/1 [==============================] - 0s 9ms/step - loss: 1051.0007
Epoch 4/10
1/1 [==============================] - 0s 3ms/step - loss: 1050.2256
Epoch 5/10
1/1 [==============================] - 0s 4ms/step - loss: 1049.4507
Epoch 6/10
1/1 [==============================] - 0s 11ms/step - loss: 1048.6760
Epoch 7/10
1/1 [==============================] - 0s 5ms/step - loss: 1047.9019
Epoch 8/10
1/1 [==============================] - 0s 6ms/step - loss: 1047.1279
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 1046.3542
Epoch 10/10
1/1 [==============================] - 0s 5ms/step - loss: 1045.5811


In [5]:
print(y)

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [6]:
model.predict(x).reshape(-1)

array([ 9.9987574e-03, -9.7591645e-01, -1.9618316e+00, -2.9477468e+00,
       -3.9336619e+00, -4.9195771e+00, -5.9054923e+00, -6.8914075e+00,
       -7.8773227e+00, -8.8632383e+00, -9.8491535e+00, -1.0835069e+01,
       -1.1820984e+01, -1.2806899e+01, -1.3792814e+01, -1.4778729e+01,
       -1.5764645e+01, -1.6750561e+01, -1.7736475e+01, -1.8722389e+01],
      dtype=float32)

In [ ]:
## 모델링 : Sequential API

# 1번. 세션 클리어 : 기존의 모델이 남아있다면 지워줘!
keras.backend.clear_session()

# 2번. 레이어 블록을 쌓을 발판 생성 : 레고처럼 차곡차곡
model = keras.models.Sequential()

# 3번. 레이어 블록 조립
model.add( keras.layers.Input(shape=(1,)))
model.add( keras.layers.Dense(1))

# 4번. 컴파일
model.compile(loss='mse', optimizer='adam')

In [ ]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 272ms/step - loss: 116.3805
Epoch 2/10
1/1 [==============================] - 0s 8ms/step - loss: 116.1233
Epoch 3/10
1/1 [==============================] - 0s 6ms/step - loss: 115.8663
Epoch 4/10
1/1 [==============================] - 0s 9ms/step - loss: 115.6097
Epoch 5/10
1/1 [==============================] - 0s 6ms/step - loss: 115.3534
Epoch 6/10
1/1 [==============================] - 0s 7ms/step - loss: 115.0973
Epoch 7/10
1/1 [==============================] - 0s 6ms/step - loss: 114.8416
Epoch 8/10
1/1 [==============================] - 0s 6ms/step - loss: 114.5862
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 114.3311
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 114.0764


In [ ]:
y_pred = model.predict(x)

y_pred[:5].reshape(-1)

array([0.00999617, 0.9734445 , 1.9368929 , 2.9003413 , 3.8637896 ],
      dtype=float32)

In [ ]:
y[:5]

array([-1,  1,  3,  5,  7])

## Now, Your turn!

In [7]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [32]:
x = np.array(range(0,20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [37]:
keras.backend.clear_session()

model = keras.models.Sequential()

model.add( keras.layers.Input(shape=(1,)))
model.add( keras.layers.Dense(1))

model.compile(loss='mse', optimizer='adam')

In [38]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 204ms/step - loss: 294.4389
Epoch 2/10
1/1 [==============================] - 0s 7ms/step - loss: 294.0530
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 293.6674
Epoch 4/10
1/1 [==============================] - 0s 4ms/step - loss: 293.2820
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 292.8969
Epoch 6/10
1/1 [==============================] - 0s 5ms/step - loss: 292.5121
Epoch 7/10
1/1 [==============================] - 0s 4ms/step - loss: 292.1277
Epoch 8/10
1/1 [==============================] - 0s 4ms/step - loss: 291.7436
Epoch 9/10
1/1 [==============================] - 0s 4ms/step - loss: 291.3598
Epoch 10/10
1/1 [==============================] - 0s 4ms/step - loss: 290.9763


In [39]:
model.predict(x)[:5].reshape(-1)

array([-0.00999697, -0.77898926, -1.5479816 , -2.3169737 , -3.085966  ],
      dtype=float32)

In [40]:
y[:5]

array([10,  7,  4,  1, -2])

## Quick Logistic Regression!

In [41]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [42]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [48]:
x.shape, y.shape

((20,), (20,))

In [43]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# model에 순차적으로 레이어를 쌓아가겠다는 의도!
model = keras.models.Sequential()

# model에 인풋 값을 받는 레이어를 넣음
model.add( keras.layers.Input(shape=(1,)) )
# model에 Dense 레이어를 넣을거야 (최초의 레이어) : weight를 곱하고, bias를 더해주는 과정
model.add( keras.layers.Dense(1, activation='sigmoid') )


# 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,), activation='sigmoid') )

# 컴파일 해주렴
model.compile(loss = 'binary_crossentropy',
              optimizer = 'adam',
              metrics=['accuracy'])

In [44]:
# 데이터를 넣어서 학습시키자!
model.fit(x[:15], y[:15], epochs=10, verbose=1)

# 결과 출력해줘!
print(y[15:])
print(model.predict(x[15:]))

Epoch 1/10
1/1 [==============================] - 0s 302ms/step - loss: 1.7460 - accuracy: 0.4000
Epoch 2/10
1/1 [==============================] - 0s 7ms/step - loss: 1.7426 - accuracy: 0.4000
Epoch 3/10
1/1 [==============================] - 0s 5ms/step - loss: 1.7393 - accuracy: 0.4000
Epoch 4/10
1/1 [==============================] - 0s 5ms/step - loss: 1.7359 - accuracy: 0.4000
Epoch 5/10
1/1 [==============================] - 0s 4ms/step - loss: 1.7325 - accuracy: 0.4000
Epoch 6/10
1/1 [==============================] - 0s 4ms/step - loss: 1.7291 - accuracy: 0.4000
Epoch 7/10
1/1 [==============================] - 0s 6ms/step - loss: 1.7258 - accuracy: 0.4000
Epoch 8/10
1/1 [==============================] - 0s 8ms/step - loss: 1.7224 - accuracy: 0.4000
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 1.7190 - accuracy: 0.4000
Epoch 10/10
1/1 [==============================] - 0s 5ms/step - loss: 1.7156 - accuracy: 0.4000


[1 1 1 1 1]
[[0.9996438 ]
 [0.99979025]
 [0.99987656]
 [0.99992734]
 [0.9999572 ]]


In [46]:
model.predict(x).reshape(-1)

array([0.49750036, 0.62714106, 0.74076366, 0.82919204, 0.89186   ,
       0.93338275, 0.9596827 , 0.9758681 , 0.98565304, 0.99150485,
       0.9949821 , 0.9970403 , 0.99825567, 0.99897254, 0.999395  ,
       0.9996438 , 0.99979025, 0.99987656, 0.99992734, 0.9999572 ],
      dtype=float32)

In [47]:
y.reshape(-1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [68]:
## 모델링 : Sequential API

# 1번 세션 클리어
keras.backend.clear_session()

# 2번 레이어 블록 발판 생성 : 차곡차곡 쌓을거야
model = keras.models.Sequential()

# 3번 .add()
model.add( keras.layers.Input(shape=(1,)))
model.add( keras.layers.Dense(1, activation='sigmoid'))

# 4번 .compile()
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [69]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 272ms/step - loss: 2.4147 - accuracy: 0.5500
Epoch 2/10
1/1 [==============================] - 0s 7ms/step - loss: 2.4121 - accuracy: 0.5500
Epoch 3/10
1/1 [==============================] - 0s 5ms/step - loss: 2.4094 - accuracy: 0.5500
Epoch 4/10
1/1 [==============================] - 0s 6ms/step - loss: 2.4067 - accuracy: 0.5500
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 2.4041 - accuracy: 0.5500
Epoch 6/10
1/1 [==============================] - 0s 4ms/step - loss: 2.4014 - accuracy: 0.5500
Epoch 7/10
1/1 [==============================] - 0s 4ms/step - loss: 2.3987 - accuracy: 0.5500
Epoch 8/10
1/1 [==============================] - 0s 4ms/step - loss: 2.3961 - accuracy: 0.5500
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 2.3934 - accuracy: 0.5500
Epoch 10/10
1/1 [==============================] - 0s 4ms/step - loss: 2.3907 - accuracy: 0.5500


In [53]:
model.predict(x)[:5].reshape(-1)

array([0.5       , 0.2633174 , 0.11328727, 0.04367206, 0.01606074],
      dtype=float32)

In [54]:
y[:5]

array([0, 0, 0, 0, 0])

## Now, Your turn!

In [70]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [71]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [72]:
x.shape, y.shape

((40,), (40,))

In [75]:
keras.backend.clear_session()

model = keras.models.Sequential()

model.add( keras.layers.Input(shape=(1,)))
model.add( keras.layers.Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [77]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
2/2 [==============================] - 0s 7ms/step - loss: 7.5116 - accuracy: 0.5250
Epoch 2/10
2/2 [==============================] - 0s 6ms/step - loss: 7.5020 - accuracy: 0.5250
Epoch 3/10
2/2 [==============================] - 0s 6ms/step - loss: 7.4914 - accuracy: 0.5250
Epoch 4/10
2/2 [==============================] - 0s 6ms/step - loss: 7.4820 - accuracy: 0.5250
Epoch 5/10
2/2 [==============================] - 0s 4ms/step - loss: 7.4723 - accuracy: 0.5250
Epoch 6/10
2/2 [==============================] - 0s 5ms/step - loss: 7.4621 - accuracy: 0.5250
Epoch 7/10
2/2 [==============================] - 0s 4ms/step - loss: 7.4519 - accuracy: 0.5250
Epoch 8/10
2/2 [==============================] - 0s 4ms/step - loss: 7.4423 - accuracy: 0.5250
Epoch 9/10
2/2 [==============================] - 0s 4ms/step - loss: 7.4319 - accuracy: 0.5250
Epoch 10/10
2/2 [==============================] - 0s 2ms/step - loss: 7.4220 - accuracy: 0.5250


In [78]:
model.predict(x)[:5].reshape(-1)

array([0.4951528 , 0.8231971 , 0.95671546, 0.99055946, 0.99799645],
      dtype=float32)

In [79]:
y[:5].reshape(-1)

array([0, 0, 0, 0, 0])