# Keras로 Linear&Logistic Regression 조금 더 맛보기

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

# Linear Regression on 쬐금 더 어려운 데이터

In [2]:
from sklearn.datasets import load_boston

In [3]:
boston = load_boston()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [4]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [12]:
keras.backend.clear_session()

model = keras.models.Sequential()

model.add( keras.layers.Input(shape=(13,)))
model.add( keras.layers.Dense(1)) # activation default = 'linear'

model.compile(loss='mse', optimizer='adam')

In [13]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 89994.3516
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 81487.9141
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 73466.2969
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 66033.3516
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 59248.3047
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 52954.8555
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 47192.7773
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 41957.6797
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 37171.1562
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 32866.0586


In [14]:
model.predict(x)[:5].reshape(-1)

array([-142.95715, -124.0558 , -130.21925, -132.5078 , -129.54214],
      dtype=float32)

In [15]:
y[:5].reshape(-1)

array([24. , 21.6, 34.7, 33.4, 36.2])

# Logistic Regression 쬐금 더 어려운 데이터

In [16]:
from sklearn.datasets import load_breast_cancer

In [17]:
cancer = load_breast_cancer()

In [19]:
x = cancer.data
y = cancer.target

# 모양 확인해볼 것
x.shape, y.shape

((569, 30), (569,))

In [37]:
from tensorflow.python import metrics
keras.backend.clear_session()

model = keras.models.Sequential()

model.add( keras.layers.Input(shape=(30,)))
model.add( keras.layers.Dense(1, activation='sigmoid'))

#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.compile(loss=keras.losses.BinaryCrossentropy(), optimizer='adam', metrics=['accuracy'])

In [39]:
model.fit(x, y, epochs=100, verbose=1)

Epoch 1/100
18/18 [==============================] - 0s 2ms/step - loss: 1.2697 - accuracy: 0.9069
Epoch 2/100
18/18 [==============================] - 0s 2ms/step - loss: 1.2680 - accuracy: 0.9069
Epoch 3/100
18/18 [==============================] - 0s 2ms/step - loss: 1.2642 - accuracy: 0.8981
Epoch 4/100
18/18 [==============================] - 0s 2ms/step - loss: 1.2814 - accuracy: 0.9086
Epoch 5/100
18/18 [==============================] - 0s 2ms/step - loss: 1.2568 - accuracy: 0.9016
Epoch 6/100
18/18 [==============================] - 0s 2ms/step - loss: 1.2683 - accuracy: 0.8981
Epoch 7/100
18/18 [==============================] - 0s 2ms/step - loss: 1.2584 - accuracy: 0.9016
Epoch 8/100
18/18 [==============================] - 0s 2ms/step - loss: 1.2478 - accuracy: 0.9104
Epoch 9/100
18/18 [==============================] - 0s 3ms/step - loss: 1.2524 - accuracy: 0.9086
Epoch 10/100
18/18 [==============================] - 0s 2ms/step - loss: 1.2459 - accuracy: 0.9086
Epoch 11/

In [29]:
model.predict(x)[:5].reshape(-1)

array([1.0000000e+00, 1.4373332e-07, 1.3636936e-13, 1.0000000e+00,
       5.8600563e-35], dtype=float32)

In [30]:
y[:5].reshape(-1)

array([0, 0, 0, 0, 0])