# Keras로 Linear&Logistic Regression 조금 더 맛보기

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

# Linear Regression on 쬐금 더 어려운 데이터

In [2]:
from sklearn.datasets import load_boston

In [3]:
boston = load_boston()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [4]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [7]:
keras.backend.clear_session()

il = keras.layers.Input(shape=(13,))
ol = keras.layers.Dense(1)(il)

model = keras.models.Model(il, ol)

model.compile(optimizer='adam', loss='mse')

In [8]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
16/16 [==============================] - 1s 2ms/step - loss: 32390.7324
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 27877.7715
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 23822.6602
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 20362.7070
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 17408.7031
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 14923.8369
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 12848.8291
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 11161.1270
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 9726.5820
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 8624.0000


In [9]:
model.predict(x)[:5].reshape(-1)

array([36.191227, 70.240135, 58.078983, 59.588264, 65.37313 ],
      dtype=float32)

In [10]:
y[:5].reshape(-1)

array([24. , 21.6, 34.7, 33.4, 36.2])

# Logistic Regression 쬐금 더 어려운 데이터

In [11]:
from sklearn.datasets import load_breast_cancer

In [12]:
cancer = load_breast_cancer()

In [13]:
x = cancer.data
y = cancer.target

# 모양 확인해볼 것
x.shape, y.shape

((569, 30), (569,))

In [16]:
from tensorflow.python import metrics
keras.backend.clear_session()

il = keras.layers.Input(shape=(30,))
ol = keras.layers.Dense(1, activation='sigmoid')(il)

model = keras.models.Model(il, ol)

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [17]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
18/18 [==============================] - 1s 2ms/step - loss: 87.0242 - accuracy: 0.6274
Epoch 2/10
18/18 [==============================] - 0s 2ms/step - loss: 68.4978 - accuracy: 0.6257
Epoch 3/10
18/18 [==============================] - 0s 2ms/step - loss: 51.2538 - accuracy: 0.5360
Epoch 4/10
18/18 [==============================] - 0s 2ms/step - loss: 40.8656 - accuracy: 0.2794
Epoch 5/10
18/18 [==============================] - 0s 2ms/step - loss: 37.3131 - accuracy: 0.1547
Epoch 6/10
18/18 [==============================] - 0s 2ms/step - loss: 36.2709 - accuracy: 0.1353
Epoch 7/10
18/18 [==============================] - 0s 2ms/step - loss: 35.3832 - accuracy: 0.1406
Epoch 8/10
18/18 [==============================] - 0s 2ms/step - loss: 34.6230 - accuracy: 0.1424
Epoch 9/10
18/18 [==============================] - 0s 2ms/step - loss: 33.8245 - accuracy: 0.1476
Epoch 10/10
18/18 [==============================] - 0s 2ms/step - loss: 33.0512 - accuracy: 0.1494


In [18]:
model.predict(x)[:5].reshape(-1)

array([1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
       1.2542829e-27], dtype=float32)

In [19]:
y[:5].reshape(-1)

array([0, 0, 0, 0, 0])