# 멀티클래스 분류 연습 (over 2진분류)

![iris_flower](https://www.embedded-robotics.com/wp-content/uploads/2022/01/Iris-Dataset-Classification-1024x367.png)

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris()

In [ ]:
x = iris.data
y = iris.target

In [ ]:
x.shape, y.shape

((150, 4), (150,))

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
# One-Hot Encoding
from tensorflow.keras.utils import to_categorical

In [ ]:
from tensorflow.keras.utils import to_categorical

In [ ]:
y = to_categorical(y, 3)

In [ ]:
y = to_categorical(y, 3)

In [ ]:
x.shape, y.shape

((150, 4), (150, 3))

# 1번. Sequential API style로 모델링 하세요

    loss = 'categorical_crossentropy' 사용!

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
keras.backend.clear_session()

model = keras.models.Sequential()

model.add( keras.layers.Input(shape=(4,)))
model.add( keras.layers.Dense(3, activation='softmax'))

model.compile( optimizer='adam', loss='categorical_crossentropy')

In [ ]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 4.0683
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 3.9732
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 3.8788
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 3.7889
Epoch 5/10
5/5 [==============================] - 0s 4ms/step - loss: 3.7064
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 3.6185
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 3.5417
Epoch 8/10
5/5 [==============================] - 0s 5ms/step - loss: 3.4650
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 3.3935
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 3.3255


In [ ]:
y_pred = model.predict(x)
y_pred[:5]

array([[9.9248767e-01, 6.8085841e-03, 7.0374284e-04],
       [9.8505616e-01, 1.3516631e-02, 1.4272466e-03],
       [9.8812276e-01, 1.0595769e-02, 1.2814206e-03],
       [9.8358256e-01, 1.4870439e-02, 1.5469727e-03],
       [9.9303401e-01, 6.2979413e-03, 6.6803978e-04]], dtype=float32)

In [ ]:
y_pred.argmax(axis=1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
y[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [ ]:
y.argmax(axis=1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# 2번. Functional API style로 모델링 하세요

In [ ]:
x.shape, y.shape

((150, 4), (150, 3))

In [ ]:
keras.backend.clear_session()

il = keras.layers.Input(shape=(4,))
ol = keras.layers.Dense(3, activation='softmax')(il)

model = keras.models.Model(il, ol)

model.compile(optimizer='adam', loss='categorical_crossentropy')

In [ ]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
5/5 [==============================] - 0s 4ms/step - loss: 2.3636
Epoch 2/10
5/5 [==============================] - 0s 4ms/step - loss: 2.2809
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 2.2052
Epoch 4/10
5/5 [==============================] - 0s 4ms/step - loss: 2.1267
Epoch 5/10
5/5 [==============================] - 0s 5ms/step - loss: 2.0495
Epoch 6/10
5/5 [==============================] - 0s 6ms/step - loss: 1.9745
Epoch 7/10
5/5 [==============================] - 0s 4ms/step - loss: 1.9073
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 1.8345
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 1.7698
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 1.7015


In [ ]:
y_pred = model.predict(x)
y_pred[:5]

array([[0.60370106, 0.3710899 , 0.02520904],
       [0.5281141 , 0.43704602, 0.03483984],
       [0.5879714 , 0.37987944, 0.03214922],
       [0.51641476, 0.44586223, 0.03772292],
       [0.6190126 , 0.35637227, 0.02461517]], dtype=float32)

In [ ]:
y_pred.argmax(axis=1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
y[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [ ]:
y.argmax(axis=1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])