# 1일차 Review : 같은 문제 다시 풀어보기

    학습은 10번으로!

In [ ]:
from sklearn.datasets import load_boston

In [ ]:
boston = load_boston()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [ ]:
x = boston.data
y = boston.target

In [ ]:
x.shape, y.shape

((506, 13), (506,))

In [ ]:
y[:5]

array([24. , 21.6, 34.7, 33.4, 36.2])

In [ ]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
########
# 모델링
########
keras.backend.clear_session()

model = keras.models.Sequential()

model.add( keras.layers.Input(shape=(13,)))
model.add( keras.layers.Dense(1, activation='linear'))

model.compile(optimizer='adam', loss='mse')

In [ ]:
model.summary() # bias(w0) 포함

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 14        
                                                                 
Total params: 14
Trainable params: 14
Non-trainable params: 0
_________________________________________________________________


In [ ]:
###########
# 모델 학습
###########
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 11695.6123
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 10709.5703
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 9981.0176
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 9437.8359
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 8926.9033
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 8460.4111
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 8025.5693
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 7558.6865
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 7142.4492
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 6732.2529


In [ ]:
###########
# 모델 예측
###########
y_pred = model.predict(x)
y_pred.reshape(-1)[:5]

array([ 93.11314 , 100.88233 ,  97.589035, 106.61875 , 107.97982 ],
      dtype=float32)

# 히든 레이어 추가하여 모델링!

    히든 레이어 2개를 추가하여 다시 모델링!
    히든 레이어 노드 수 : 32
    히든 레이어 activation = 'relu'

In [ ]:
from tensorflow.python.ops.gen_array_ops import shape
########
# 모델링
########
keras.backend.clear_session()

model = keras.models.Sequential()

model.add( keras.layers.Input(shape=(13,)))
model.add( keras.layers.Dense(32, activation='relu'))
model.add( keras.layers.Dense(32, activation='relu'))
model.add( keras.layers.Dense(1, activation='linear'))

model.compile(optimizer='adam', loss='mse')

In [ ]:
model.summary()
# input layer node 수 + bias = 13 + 1 = 14
# 히든레이어1 노드 수 32
# 히든레이어2 노드 수 32

# input레이어 히든레이어1
# (13 + 1) * 32 = 448

# 히든레이어1 히든레이어2
# (32 + 1) * 32 = 1056

# 히든레이어2
# (32 + 1)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                448       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1,537
Trainable params: 1,537
Non-trainable params: 0
_________________________________________________________________


In [ ]:
###########
# 모델 학습
###########
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 5553.0293
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 469.6671
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 185.6104
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 103.5972
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 74.2849
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 69.6034
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 68.2081
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 66.0912
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 64.9090
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 62.7283


In [ ]:
###########
# 모델 예측
###########
y_pred = model.predict(x)
y_pred.reshape(-1)[:5]

array([25.035934, 28.934887, 29.15205 , 30.992954, 30.89595 ],
      dtype=float32)

In [ ]:
y[:5]

array([24. , 21.6, 34.7, 33.4, 36.2])