# 1일차 Review : 같은 문제 다시 풀어보기

    학습은 10번으로!

In [3]:
from sklearn.datasets import load_iris

In [4]:
iris = load_iris()

In [17]:
x = iris.data
y = iris.target

In [6]:
x.shape, y.shape

((150, 4), (150,))

In [7]:
from sklearn.model_selection import train_test_split

In [22]:
### train set / test set
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2022)

In [9]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [10]:
from tensorflow.keras.utils import to_categorical

In [39]:
num_classes = len(np.unique(y))
np.unique(y)

array([0, 1, 2])

In [40]:
#######################
# 어떤 전처리 작업 필요
# Hint : y.shape
#######################
y_train = to_categorical(y_train, num_classes=num_classes)
y_test = to_categorical(y_test, num_classes=num_classes)

In [25]:
from tensorflow.python import metrics
########
# 모델링
########
keras.backend.clear_session()

model = keras.models.Sequential()

model.add( keras.layers.Input(shape=(4,)))
model.add( keras.layers.Dense(3, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [26]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs=10, verbose=1)

Epoch 1/10
4/4 [==============================] - 1s 4ms/step - loss: 2.0967 - accuracy: 0.3417
Epoch 2/10
4/4 [==============================] - 0s 3ms/step - loss: 2.0244 - accuracy: 0.3417
Epoch 3/10
4/4 [==============================] - 0s 3ms/step - loss: 1.9475 - accuracy: 0.3417
Epoch 4/10
4/4 [==============================] - 0s 3ms/step - loss: 1.8737 - accuracy: 0.3417
Epoch 5/10
4/4 [==============================] - 0s 3ms/step - loss: 1.8057 - accuracy: 0.3417
Epoch 6/10
4/4 [==============================] - 0s 3ms/step - loss: 1.7395 - accuracy: 0.3417
Epoch 7/10
4/4 [==============================] - 0s 3ms/step - loss: 1.6711 - accuracy: 0.3417
Epoch 8/10
4/4 [==============================] - 0s 4ms/step - loss: 1.6063 - accuracy: 0.3417
Epoch 9/10
4/4 [==============================] - 0s 4ms/step - loss: 1.5440 - accuracy: 0.3417
Epoch 10/10
4/4 [==============================] - 0s 5ms/step - loss: 1.4884 - accuracy: 0.3417


In [27]:
###########
# 모델 예측
###########
y_pred = model.predict(x_test)
y_pred

array([[0.57618093, 0.25714105, 0.16667803],
       [0.7438519 , 0.15313894, 0.1030092 ],
       [0.95305055, 0.01614578, 0.03080364],
       [0.67718375, 0.2052196 , 0.11759668],
       [0.9623523 , 0.0117029 , 0.02594483],
       [0.93728083, 0.02207599, 0.04064317],
       [0.8831727 , 0.0476989 , 0.06912838],
       [0.8275435 , 0.0793023 , 0.09315419],
       [0.9670209 , 0.01036593, 0.02261315],
       [0.8668823 , 0.06633003, 0.06678765],
       [0.8039448 , 0.10750012, 0.08855504],
       [0.830058  , 0.10431002, 0.06563208],
       [0.88553315, 0.0528    , 0.06166676],
       [0.3581681 , 0.45870855, 0.18312337],
       [0.68349457, 0.18233158, 0.13417394],
       [0.9645667 , 0.01232862, 0.02310466],
       [0.81093526, 0.10520777, 0.08385695],
       [0.84638363, 0.08534924, 0.06826717],
       [0.64349306, 0.22952199, 0.12698497],
       [0.83840185, 0.07479301, 0.08680505],
       [0.977081  , 0.00572853, 0.01719042],
       [0.9355025 , 0.02207203, 0.04242542],
       [0.

In [28]:
y_pred.argmax(axis=1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
y_test

array([2, 2, 0, 2, 0, 0, 1, 1, 0, 1, 1, 2, 1, 2, 2, 0, 1, 2, 2, 1, 0, 0,
       2, 0, 2, 2, 2, 0, 1, 2])

# 히든 레이어 추가하여 모델링! (Functional API)

    히든 레이어 2개를 추가하여 다시 모델링!
    히든 레이어 노드 수 : 32
    히든 레이어 activation = 'relu'

In [33]:
########
# 모델링
########
keras.backend.clear_session()

model = keras.models.Sequential()

model.add( keras.layers.Input(shape=(4,)))
model.add( keras.layers.Dense(32, activation='relu'))
model.add( keras.layers.Dense(32, activation='relu'))
model.add( keras.layers.Dense(3, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                160       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 3)                 99        
                                                                 
Total params: 1,315
Trainable params: 1,315
Non-trainable params: 0
_________________________________________________________________


In [34]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs=10, verbose=1)

Epoch 1/10
4/4 [==============================] - 1s 5ms/step - loss: 1.1726 - accuracy: 0.3083
Epoch 2/10
4/4 [==============================] - 0s 5ms/step - loss: 1.0432 - accuracy: 0.3083
Epoch 3/10
4/4 [==============================] - 0s 4ms/step - loss: 0.9459 - accuracy: 0.4750
Epoch 4/10
4/4 [==============================] - 0s 5ms/step - loss: 0.8735 - accuracy: 0.7333
Epoch 5/10
4/4 [==============================] - 0s 4ms/step - loss: 0.8183 - accuracy: 0.8500
Epoch 6/10
4/4 [==============================] - 0s 6ms/step - loss: 0.7705 - accuracy: 0.8000
Epoch 7/10
4/4 [==============================] - 0s 6ms/step - loss: 0.7344 - accuracy: 0.7250
Epoch 8/10
4/4 [==============================] - 0s 6ms/step - loss: 0.6999 - accuracy: 0.7667
Epoch 9/10
4/4 [==============================] - 0s 5ms/step - loss: 0.6694 - accuracy: 0.8083
Epoch 10/10
4/4 [==============================] - 0s 5ms/step - loss: 0.6408 - accuracy: 0.8500


In [35]:
###########
# 모델 예측
###########
y_pred = model.predict(x_test)
y_pred

array([[0.06761378, 0.43472606, 0.4976602 ],
       [0.05250331, 0.46723202, 0.48026478],
       [0.6690328 , 0.17660186, 0.15436545],
       [0.07945298, 0.42837274, 0.49217424],
       [0.72628045, 0.13856706, 0.1351525 ],
       [0.65560526, 0.18108726, 0.16330747],
       [0.2592126 , 0.43107757, 0.3097099 ],
       [0.19106111, 0.45442384, 0.35451508],
       [0.7361934 , 0.13468957, 0.12911698],
       [0.19462393, 0.44480813, 0.3605679 ],
       [0.14012305, 0.44365326, 0.41622368],
       [0.07175766, 0.45170802, 0.4765343 ],
       [0.1642071 , 0.4737407 , 0.36205223],
       [0.055715  , 0.37733492, 0.5669501 ],
       [0.04340269, 0.48143962, 0.47515762],
       [0.7243852 , 0.13282283, 0.14279199],
       [0.17766926, 0.41909555, 0.40323526],
       [0.08749136, 0.48396802, 0.42854068],
       [0.07299519, 0.43032092, 0.49668387],
       [0.18433183, 0.45526484, 0.36040333],
       [0.75547045, 0.1290015 , 0.11552797],
       [0.6630851 , 0.16386417, 0.17305079],
       [0.

In [36]:
y_pred.argmax(axis=1)

array([2, 2, 0, 2, 0, 0, 1, 1, 0, 1, 1, 2, 1, 2, 1, 0, 1, 1, 2, 1, 0, 0,
       2, 0, 2, 1, 2, 0, 1, 1])

In [42]:
y_test.argmax(axis=1)

array([2, 2, 0, 2, 0, 0, 1, 1, 0, 1, 1, 2, 1, 2, 2, 0, 1, 2, 2, 1, 0, 0,
       2, 0, 2, 2, 2, 0, 1, 2])