# 1일차 Review : 같은 문제 다시 풀어보기

    학습은 10번으로!

In [1]:
from sklearn.datasets import load_breast_cancer

In [2]:
cancer = load_breast_cancer()

In [3]:
x = cancer.data
y = cancer.target

In [4]:
x.shape, y.shape

((569, 30), (569,))

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
### train set / test set
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2022)

In [7]:
x_train.shape, x_test.shape

((455, 30), (114, 30))

In [8]:
y_train.shape, y_test.shape

((455,), (114,))

In [9]:
y_train[:5]

array([1, 0, 0, 1, 0])

In [10]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [27]:
########
# 모델링
########
keras.backend.clear_session()

il = keras.layers.Input(shape=(30,), name='input')
ol = keras.layers.Dense(1, activation='sigmoid', name='output')(il)

model = keras.models.Model(inputs = il, outputs = ol)

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [28]:
model.summary() # 31 + 1(bias)

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input (InputLayer)          [(None, 30)]              0         
                                                                 
 output (Dense)              (None, 1)                 31        
                                                                 
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [22]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs=10, verbose=1)

Epoch 1/10
15/15 [==============================] - 1s 2ms/step - loss: 158.5726 - accuracy: 0.3626
Epoch 2/10
15/15 [==============================] - 0s 2ms/step - loss: 146.7894 - accuracy: 0.3626
Epoch 3/10
15/15 [==============================] - 0s 2ms/step - loss: 134.5487 - accuracy: 0.3626
Epoch 4/10
15/15 [==============================] - 0s 2ms/step - loss: 122.5633 - accuracy: 0.3626
Epoch 5/10
15/15 [==============================] - 0s 2ms/step - loss: 110.6703 - accuracy: 0.3626
Epoch 6/10
15/15 [==============================] - 0s 2ms/step - loss: 98.4519 - accuracy: 0.3626
Epoch 7/10
15/15 [==============================] - 0s 2ms/step - loss: 86.4811 - accuracy: 0.3626
Epoch 8/10
15/15 [==============================] - 0s 2ms/step - loss: 74.1329 - accuracy: 0.3626
Epoch 9/10
15/15 [==============================] - 0s 2ms/step - loss: 62.1458 - accuracy: 0.3626
Epoch 10/10
15/15 [==============================] - 0s 2ms/step - loss: 49.8324 - accuracy: 0.3626


In [26]:
###########
# 모델 예측
###########
y_pred = model.predict(x_test)
y_pred[:5]

array([[1.8618287e-11],
       [1.7551315e-19],
       [1.8992202e-26],
       [2.9092874e-32],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.8575930e-08],
       [1.0203529e-09],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [4.1431056e-34],
       [5.2521817e-19],
       [9.0322316e-27],
       [0.0000000e+00],
       [3.0846724e-38],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.6620555e-24],
       [4.2795679e-33],
       [0.0000000e+00],
       [4.0080050e-31],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.8487811e-01],
       [0.0000000e+00],
       [1.4810873e-30],
       [6.8749630e-24],
       [5.2145749e-02],
       [7.7912430e-32],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.4240779e-07],
       [0.000000

In [25]:
y_test[:5]

array([1, 1, 1, 0, 0])

# 히든 레이어 추가하여 모델링!

    히든 레이어 2개를 추가하여 다시 모델링!
    히든 레이어 노드 수 : 32
    히든 레이어 activation = 'relu'

In [32]:
########
# 모델링
########
keras.backend.clear_session()

il = keras.layers.Input(shape=(30,), name='input')
hl1 = keras.layers.Dense(32, activation='relu', name='hidden1')(il)
hl2 = keras.layers.Dense(32, activation='relu', name='hidden2')(hl1)
ol = keras.layers.Dense(1, activation='sigmoid', name='output')(hl2)

model = keras.models.Model(inputs = il, outputs = ol)

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input (InputLayer)          [(None, 30)]              0         
                                                                 
 hidden1 (Dense)             (None, 32)                992       
                                                                 
 hidden2 (Dense)             (None, 32)                1056      
                                                                 
 output (Dense)              (None, 1)                 33        
                                                                 
Total params: 2,081
Trainable params: 2,081
Non-trainable params: 0
_________________________________________________________________


In [33]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs=10, verbose=1)

Epoch 1/10
15/15 [==============================] - 1s 3ms/step - loss: 1.4379 - accuracy: 0.7319
Epoch 2/10
15/15 [==============================] - 0s 2ms/step - loss: 0.6075 - accuracy: 0.8769
Epoch 3/10
15/15 [==============================] - 0s 2ms/step - loss: 0.4202 - accuracy: 0.8879
Epoch 4/10
15/15 [==============================] - 0s 3ms/step - loss: 0.3320 - accuracy: 0.9077
Epoch 5/10
15/15 [==============================] - 0s 3ms/step - loss: 0.3571 - accuracy: 0.8989
Epoch 6/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2966 - accuracy: 0.9099
Epoch 7/10
15/15 [==============================] - 0s 2ms/step - loss: 0.3666 - accuracy: 0.8967
Epoch 8/10
15/15 [==============================] - 0s 2ms/step - loss: 0.3874 - accuracy: 0.8923
Epoch 9/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2959 - accuracy: 0.9143
Epoch 10/10
15/15 [==============================] - 0s 2ms/step - loss: 0.3029 - accuracy: 0.9143


In [35]:
###########
# 모델 예측
###########
y_pred = model.predict(x_test)
y_pred[:5]

array([[0.9985633 ],
       [0.9999536 ],
       [0.9994177 ],
       [0.8434217 ],
       [0.00580168]], dtype=float32)

In [43]:
y_pred2 = np.where(y_pred >= 0.5, 1, 0)
y_pred2.reshape(-1)

array([1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1])

In [45]:
y_test

array([1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1])